/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EditorChangeEvent } from "./components/db-quill-editor-component/quill-editor.types";
import { EditorChangeEvent as EditorChangeEvent1 } from "./components/db-tinymce-editor-component/db-tinymce.types";
export { EditorChangeEvent } from "./components/db-quill-editor-component/quill-editor.types";
export { EditorChangeEvent as EditorChangeEvent1 } from "./components/db-tinymce-editor-component/db-tinymce.types";
export namespace Components {
    interface DbQuillEditor {
        "disableToolbar": boolean;
        "editorHeight": string;
        "editorWidth": string;
        "id": string|null;
        "initalEditorHtmlContent": string|null;
        "initialEditorTextContent": string|null;
        "readOnly": boolean;
        "toolbarConfigString": string;
    }
    interface DbSummernoteEditorComponent {
        "disableToolbar": boolean;
        "editorHTMLContent": string;
        "editorHeight": string;
        "editorWidth": string;
        "id": string;
        "placeholder": string;
        "readOnly": boolean;
        "toolbarConfigString": string;
    }
    interface DbTinymceEditor {
        "autoCompleteWordsString": string;
        "baseUrl": string;
        "disableStatusBar": boolean;
        "disableToolbar": boolean;
        "editorHTMLContent": string;
        "editorHeight": string;
        "editorTextContent": string;
        "editorWidth": string;
        "enableAutoComplete": boolean;
        "id": string;
        "placeholder": string;
        "readOnly": boolean;
        "toolbarConfigString": string;
    }
    interface StencilSandboxEditor {
        "disableToolbar": boolean;
        "editorHTMLContent": string;
        "editorHeight": string;
        "editorWidth": 'string';
        "placeholder": string;
        "readOnly": boolean;
        "toolbarConfigString": string;
    }
}
export interface DbQuillEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDbQuillEditorElement;
}
export interface DbSummernoteEditorComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDbSummernoteEditorComponentElement;
}
export interface DbTinymceEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDbTinymceEditorElement;
}
export interface StencilSandboxEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilSandboxEditorElement;
}
declare global {
    interface HTMLDbQuillEditorElement extends Components.DbQuillEditor, HTMLStencilElement {
    }
    var HTMLDbQuillEditorElement: {
        prototype: HTMLDbQuillEditorElement;
        new (): HTMLDbQuillEditorElement;
    };
    interface HTMLDbSummernoteEditorComponentElement extends Components.DbSummernoteEditorComponent, HTMLStencilElement {
    }
    var HTMLDbSummernoteEditorComponentElement: {
        prototype: HTMLDbSummernoteEditorComponentElement;
        new (): HTMLDbSummernoteEditorComponentElement;
    };
    interface HTMLDbTinymceEditorElement extends Components.DbTinymceEditor, HTMLStencilElement {
    }
    var HTMLDbTinymceEditorElement: {
        prototype: HTMLDbTinymceEditorElement;
        new (): HTMLDbTinymceEditorElement;
    };
    interface HTMLStencilSandboxEditorElement extends Components.StencilSandboxEditor, HTMLStencilElement {
    }
    var HTMLStencilSandboxEditorElement: {
        prototype: HTMLStencilSandboxEditorElement;
        new (): HTMLStencilSandboxEditorElement;
    };
    interface HTMLElementTagNameMap {
        "db-quill-editor": HTMLDbQuillEditorElement;
        "db-summernote-editor-component": HTMLDbSummernoteEditorComponentElement;
        "db-tinymce-editor": HTMLDbTinymceEditorElement;
        "stencil-sandbox-editor": HTMLStencilSandboxEditorElement;
    }
}
declare namespace LocalJSX {
    interface DbQuillEditor {
        "disableToolbar"?: boolean;
        "editorHeight"?: string;
        "editorWidth"?: string;
        "id"?: string|null;
        "initalEditorHtmlContent"?: string|null;
        "initialEditorTextContent"?: string|null;
        "onEditorchange"?: (event: DbQuillEditorCustomEvent<EditorChangeEvent>) => void;
        "readOnly"?: boolean;
        "toolbarConfigString": string;
    }
    interface DbSummernoteEditorComponent {
        "disableToolbar"?: boolean;
        "editorHTMLContent"?: string;
        "editorHeight"?: string;
        "editorWidth"?: string;
        "id"?: string;
        "onContent-change"?: (event: DbSummernoteEditorComponentCustomEvent<{htmlContent:string}>) => void;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "toolbarConfigString"?: string;
    }
    interface DbTinymceEditor {
        "autoCompleteWordsString"?: string;
        "baseUrl"?: string;
        "disableStatusBar"?: boolean;
        "disableToolbar"?: boolean;
        "editorHTMLContent"?: string;
        "editorHeight"?: string;
        "editorTextContent"?: string;
        "editorWidth"?: string;
        "enableAutoComplete"?: boolean;
        "id"?: string;
        "onContent-change"?: (event: DbTinymceEditorCustomEvent<EditorChangeEvent1>) => void;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "toolbarConfigString": string;
    }
    interface StencilSandboxEditor {
        "disableToolbar"?: boolean;
        "editorHTMLContent"?: string;
        "editorHeight"?: string;
        "editorWidth"?: 'string';
        "onContent-change"?: (event: StencilSandboxEditorCustomEvent<{htmlContent:string}>) => void;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "toolbarConfigString"?: string;
    }
    interface IntrinsicElements {
        "db-quill-editor": DbQuillEditor;
        "db-summernote-editor-component": DbSummernoteEditorComponent;
        "db-tinymce-editor": DbTinymceEditor;
        "stencil-sandbox-editor": StencilSandboxEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "db-quill-editor": LocalJSX.DbQuillEditor & JSXBase.HTMLAttributes<HTMLDbQuillEditorElement>;
            "db-summernote-editor-component": LocalJSX.DbSummernoteEditorComponent & JSXBase.HTMLAttributes<HTMLDbSummernoteEditorComponentElement>;
            "db-tinymce-editor": LocalJSX.DbTinymceEditor & JSXBase.HTMLAttributes<HTMLDbTinymceEditorElement>;
            "stencil-sandbox-editor": LocalJSX.StencilSandboxEditor & JSXBase.HTMLAttributes<HTMLStencilSandboxEditorElement>;
        }
    }
}
