/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EditorChangeEvent } from "./components/db-tinymce-editor-component/db-tinymce.types";
export { EditorChangeEvent } from "./components/db-tinymce-editor-component/db-tinymce.types";
export namespace Components {
    interface DbSandboxEditor {
        "disableToolbar": boolean;
        "editorHTMLContent": string;
        "editorHeight": string;
        "editorWidth": 'string';
        "placeholder": string;
        "readOnly": boolean;
        "toolbarConfigString": string;
    }
    interface DbTinymceEditor {
        "autoCompleteWordsString": string;
        "baseUrl": string;
        "disableStatusBar": boolean;
        "disableToolbar": boolean;
        "editorHTMLContent": string;
        "editorHeight": string;
        "editorTextContent": string;
        "editorWidth": string;
        "enableAutoComplete": boolean;
        "id": string;
        "placeholder": string;
        "readOnly": boolean;
        "toolbarConfigString": string;
    }
}
export interface DbSandboxEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDbSandboxEditorElement;
}
export interface DbTinymceEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDbTinymceEditorElement;
}
declare global {
    interface HTMLDbSandboxEditorElement extends Components.DbSandboxEditor, HTMLStencilElement {
    }
    var HTMLDbSandboxEditorElement: {
        prototype: HTMLDbSandboxEditorElement;
        new (): HTMLDbSandboxEditorElement;
    };
    interface HTMLDbTinymceEditorElement extends Components.DbTinymceEditor, HTMLStencilElement {
    }
    var HTMLDbTinymceEditorElement: {
        prototype: HTMLDbTinymceEditorElement;
        new (): HTMLDbTinymceEditorElement;
    };
    interface HTMLElementTagNameMap {
        "db-sandbox-editor": HTMLDbSandboxEditorElement;
        "db-tinymce-editor": HTMLDbTinymceEditorElement;
    }
}
declare namespace LocalJSX {
    interface DbSandboxEditor {
        "disableToolbar"?: boolean;
        "editorHTMLContent"?: string;
        "editorHeight"?: string;
        "editorWidth"?: 'string';
        "onContent-change"?: (event: DbSandboxEditorCustomEvent<{htmlContent:string}>) => void;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "toolbarConfigString"?: string;
    }
    interface DbTinymceEditor {
        "autoCompleteWordsString"?: string;
        "baseUrl"?: string;
        "disableStatusBar"?: boolean;
        "disableToolbar"?: boolean;
        "editorHTMLContent"?: string;
        "editorHeight"?: string;
        "editorTextContent"?: string;
        "editorWidth"?: string;
        "enableAutoComplete"?: boolean;
        "id"?: string;
        "onContent-change"?: (event: DbTinymceEditorCustomEvent<EditorChangeEvent>) => void;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "toolbarConfigString": string;
    }
    interface IntrinsicElements {
        "db-sandbox-editor": DbSandboxEditor;
        "db-tinymce-editor": DbTinymceEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "db-sandbox-editor": LocalJSX.DbSandboxEditor & JSXBase.HTMLAttributes<HTMLDbSandboxEditorElement>;
            "db-tinymce-editor": LocalJSX.DbTinymceEditor & JSXBase.HTMLAttributes<HTMLDbTinymceEditorElement>;
        }
    }
}
